### ISSUE TITLE
infer.py error

### ISSUE THREAD

**Issue by gengkai258** [ljanyst/ssd-tensorflow#21]
ubuntu@ubuntu-IdeaPad-U430p:~/git/ssd-tensorflow-master$ ./infer.py pascal-voc/test/VOCdevkit/VOC2007/JPEGImages
[i] Project name:       test
[i] Training data:      pascal-voc/training-data.pkl
[i] Batch size:         4
[i] Data source:        None
[i] Data directory:     pascal-voc
[i] Output directory:   test-output
[i] Annotate:           False
[i] Dump predictions:   False
[i] Sample:             test
[i] Threshold:          0.01
[i] Pascal summary:     False
[i] Configuring the data source...
[!] Unable to load data source: No module named 'source_None'
ubuntu@ubuntu-IdeaPad-U430p:~/git/ssd-tensorflow-master$ ./infer.py pascal-voc/test/VOCdevkit/VOC2007/JPEGImages
[i] Project name:       test
[i] Training data:      pascal-voc/training-data.pkl
[i] Batch size:         4
[i] Data source:        None
[i] Data directory:     pascal-voc
[i] Output directory:   test-output
[i] Annotate:           False
[i] Dump predictions:   False
[i] Sample:             test
[i] Threshold:          0.01
[i] Pascal summary:     False
[i] Compute stats:      False
[i] Network checkpoint: test/final.ckpt
[i] Metagraph file:     test/final.ckpt.meta
[i] Image size:         Size(w=300, h=300)
[i] Number of files:    1
2018-04-07 21:04:04.761128: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-04-07 21:04:04.761153: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-04-07 21:04:04.761171: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-04-07 21:04:04.761180: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-04-07 21:04:04.761190: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-04-07 21:04:04.910995: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-04-07 21:04:04.911423: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GT 730M
major: 3 minor: 5 memoryClockRate (GHz) 0.758
pciBusID 0000:09:00.0
Total memory: 1.96GiB
Free memory: 1.71GiB
2018-04-07 21:04:04.911458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2018-04-07 21:04:04.911468: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2018-04-07 21:04:04.911486: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GT 730M, pci bus id: 0000:09:00.0)
[i] Creating the model...
[i] Processing samples:   0%|                                                                           | 0/1 [00:00<?, ?batches/s]OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /io/opencv/modules/imgproc/src/resize.cpp, line 4044
Traceback (most recent call last):
  File "./infer.py", line 281, in <module>
    sys.exit(main())
  File "./infer.py", line 220, in main
    desc=description, unit='batches'):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 897, in __iter__
    for obj in iterable:
  File "./infer.py", line 47, in sample_generator
    image = cv2.resize(cv2.imread(image_file), image_size)
cv2.error: /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

someone can help me ?  thank you very much !

**Comment by ljanyst** [comment]
You need to give a list of files to this tool, not a directory.

**Comment by RoseLii** [comment]
please help me,I also encountered the same problem。How to solve it? @gengkai258 @ljanyst
