### ISSUE TITLE
how to use detect.py

### ISSUE THREAD

**Issue by futurianh1k** [ljanyst/ssd-tensorflow#23]
Hi Lukas, could you please tell me how to use detect.py?

I exported a model to a pb file, and tried to use detect.py.
I used images with 1280*1024 pixels, but I faced cv2 error.

Please help

2018-04-11 17:03:33.415491: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9886 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1)
  0%|                                                                                                             | 0/1 [00:00<?, ?it/s]OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /home/kimken/opencv-3.4.0/modules/imgproc/src/resize.cpp, line 4044

Traceback (most recent call last):
  File "detect.py", line 124, in <module>
    main()
  File "detect.py", line 99, in main
    img = cv2.resize(img, (300, 300))
cv2.error: /home/kimken/opencv-3.4.0/modules/imgproc/src/resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

**Comment by futurianh1k** [comment]
I found how to use it.  Thank you !    The fisrt argument is    directory/*
