### ISSUE TITLE
Can't pickle local object 'TrainingData.__batch_generator.<locals>.batch_producer'

### ISSUE THREAD

**Issue by MulinYu** [ljanyst/ssd-tensorflow#28]
runfile('G:/ssd-tensorflow/train.py', wdir='G:/ssd-tensorflow')
[i] Project name:          test
[i] Data directory:        pascal-voc
[i] VGG directory:         vgg_graph
[i] # epochs:              200
[i] Batch size:            8
[i] Tensorboard directory: tb
[i] Checkpoint interval:   5
[i] Learning rate values:  0.001;0.0001;0.00001
[i] Learning rate boundaries:  320000;400000
[i] Momentum:              0.9
[i] Weight decay:          0.0005
[i] Continue:              False
[i] Number of workers:     8
[i] Creating directory test...
[i] Starting at epoch:     1
[i] Configuring the training data...
[i] # training samples:    21503
[i] # validation samples:  17125
[i] # classes:             20
[i] Image size:            Size(w=300, h=300)
[i] Creating the model...
INFO:tensorflow:Restoring parameters from b'vgg_graph/vgg\\variables\\variables'
WARNING:tensorflow:From C:\ProgramData\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
[i] Training...
[i] Train  1/200:   0%|          | 0/2688 [00:00<?, ?batches/s]Traceback (most recent call last):

  File "<ipython-input-1-77161caa0548>", line 1, in <module>
    runfile('G:/ssd-tensorflow/train.py', wdir='G:/ssd-tensorflow')

  File "C:\ProgramData\Anaconda\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "G:/ssd-tensorflow/train.py", line 344, in <module>
    sys.exit(main())

  File "G:/ssd-tensorflow/train.py", line 253, in main
    desc=description, unit='batches'):

  File "C:\ProgramData\Anaconda\envs\tensorflow\lib\site-packages\tqdm\_tqdm.py", line 927, in __iter__
    for obj in iterable:

  File "G:\ssd-tensorflow\training_data.py", line 172, in gen_batch
    w.start()

  File "C:\ProgramData\Anaconda\envs\tensorflow\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)

  File "C:\ProgramData\Anaconda\envs\tensorflow\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "C:\ProgramData\Anaconda\envs\tensorflow\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)

  File "C:\ProgramData\Anaconda\envs\tensorflow\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)

  File "C:\ProgramData\Anaconda\envs\tensorflow\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)

AttributeError: Can't pickle local object 'TrainingData.__batch_generator.<locals>.batch_producer'

I train this model in windows10, but after create the model, it says "can't pickle", it's the problem of vision?

**Comment by ljanyst** [comment]
Parallel training is enabled by default and only supported on Linux and MacOS. You choices are to disable parallel processing (there is a commandline option for that - not recommended) or not use Windows (recommended).

**Comment by MulinYu** [comment]
thx
