### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by vladtamas** [ljanyst/ssd-tensorflow#3]
Hello,

I'm getting an error as you can see in the log below. Can you tell me what is wrong?

[i] Epoch  1/10:   0%|                                                                                                              | 0/3302 [00:00<?, ?batches/s]Traceback (most recent call last):
  File "train.py", line 327, in <module>
    sys.exit(main())
  File "train.py", line 241, in main
    desc=description, unit='batches'):
  File "C:\Users\vlad.tamas\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\tqdm\_tqdm.py", line 955, in __iter__
    for obj in iterable:
  File "D:\ssd-tensorflow-master\training_data.py", line 166, in gen_batch
    w.start()
  File "C:\Users\vlad.tamas\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\vlad.tamas\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\vlad.tamas\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\vlad.tamas\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\vlad.tamas\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'TrainingData.__batch_generator.<locals>.batch_producer'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\vlad.tamas\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\vlad.tamas\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
EOFError: Ran out of input

**Comment by ljanyst** [comment]
The generators use POSIX shared memory to improve performance. I am not sure if that works on Windows at all, I have never tried it. Another reason might be the python version - the program has been written for python3.

**Comment by ljanyst** [comment]
You may try to run the training without parallelism, but it will likely be pretty slow. Pass the `--num-workers 0` parameter to `train.py`. https://github.com/ljanyst/ssd-tensorflow/blob/master/train.py#L76

**Comment by ljanyst** [comment]
This problem is fixed by setting the number of workers to 0 or using Linux or Mac instead.
See https://github.com/ljanyst/ssd-tensorflow/issues/3 .
