### ISSUE TITLE
Error when training: "OpenCV Error: Assertion failed ((scn == 3 || scn == 4) && (depth == 0 || depth == 5)) in cvtColor, file /tmp/build/80754af9/opencv_1525313247723/work/modules/imgproc/src/color.cpp, line 11115 Process Process-34:"

### ISSUE THREAD

**Issue by dauxubk** [ljanyst/ssd-tensorflow#33]
Hi,
I just use train.py but when start training I get the error :
"[i] Train  1/200:   0%|                                                                                                                                                | 0/2688 [00:00<?, ?batches/s]**OpenCV Error: Assertion failed ((scn == 3 || scn == 4) && (depth == 0 || depth == 5)) in cvtColor, file** /tmp/build/80754af9/opencv_1525313247723/work/modules/imgproc/src/color.cpp, line 11115
Process Process-34:
Traceback (most recent call last):
  File "/home/hientt/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/hientt/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 119, in batch_producer
    images, labels, gt_boxes = process_samples(samples)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 95, in process_samples
    image, label, gt = run_transforms(s)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 83, in run_transforms
    args = t(*args)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 159, in __call__
    return self.transforms[pick](data, label, gt)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 148, in __call__
    args = t(*args)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 136, in __call__
    return self.transform(data, label, gt)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 215, in __call__
    data = cv2.cvtColor(data, cv2.COLOR_BGR2HSV)
cv2.error: /tmp/build/80754af9/opencv_1525313247723/work/modules/imgproc/src/color.cpp:11115: error: (-215) (scn == 3 || scn == 4) && (depth == 0 || depth == 5) in function cvtColor

Process Process-35:
Traceback (most recent call last):
  File "/home/hientt/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/hientt/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 119, in batch_producer
    images, labels, gt_boxes = process_samples(samples)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 95, in process_samples
    image, label, gt = run_transforms(s)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 83, in run_transforms
    args = t(*args)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 136, in __call__
    return self.transform(data, label, gt)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 168, in __call__
    data = data.astype(np.float32)
AttributeError: 'NoneType' object has no attribute 'astype'
OpenCV Error: Assertion failed ((scn == 3 || scn == 4) && (depth == 0 || depth == 5)) in cvtColor, file /tmp/build/80754af9/opencv_1525313247723/work/modules/imgproc/src/color.cpp, line 11115
Process Process-36:
OpenCV Error: Assertion failed ((scn == 3 || scn == 4) && (depth == 0 || depth == 5)) in cvtColor, file /tmp/build/80754af9/opencv_1525313247723/work/modules/imgproc/src/color.cpp, line 11115
OpenCV Error: Assertion failed ((scn == 3 || scn == 4) && (depth == 0 || depth == 5)) in cvtColor, file /tmp/build/80754af9/opencv_1525313247723/work/modules/imgproc/src/color.cpp, line 11115
Process Process-37:
Process Process-38:
Process Process-39:
Traceback (most recent call last):
  File "/home/hientt/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/hientt/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 119, in batch_producer
    images, labels, gt_boxes = process_samples(samples)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 95, in process_samples
    image, label, gt = run_transforms(s)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 83, in run_transforms
    args = t(*args)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 159, in __call__
    return self.transforms[pick](data, label, gt)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 148, in __call__
    args = t(*args)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 136, in __call__
    return self.transform(data, label, gt)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 215, in __call__
    data = cv2.cvtColor(data, cv2.COLOR_BGR2HSV)
cv2.error: /tmp/build/80754af9/opencv_1525313247723/work/modules/imgproc/src/color.cpp:11115: error: (-215) (scn == 3 || scn == 4) && (depth == 0 || depth == 5) in function cvtColor

Process Process-40:
Traceback (most recent call last):
Traceback (most recent call last):
Process Process-41:
  File "/home/hientt/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/hientt/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/hientt/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hientt/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 119, in batch_producer
    images, labels, gt_boxes = process_samples(samples)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 119, in batch_producer
    images, labels, gt_boxes = process_samples(samples)
Traceback (most recent call last):
  File "/home/hientt/ssd-tensorflow/training_data.py", line 95, in process_samples
    image, label, gt = run_transforms(s)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 95, in process_samples
    image, label, gt = run_transforms(s)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 83, in run_transforms
    args = t(*args)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 83, in run_transforms
    args = t(*args)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 136, in __call__
    return self.transform(data, label, gt)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 159, in __call__
    return self.transforms[pick](data, label, gt)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 148, in __call__
    args = t(*args)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 168, in __call__
    data = data.astype(np.float32)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 136, in __call__
    return self.transform(data, label, gt)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 215, in __call__
    data = cv2.cvtColor(data, cv2.COLOR_BGR2HSV)
AttributeError: 'NoneType' object has no attribute 'astype'
cv2.error: /tmp/build/80754af9/opencv_1525313247723/work/modules/imgproc/src/color.cpp:11115: error: (-215) (scn == 3 || scn == 4) && (depth == 0 || depth == 5) in function cvtColor

  File "/home/hientt/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/hientt/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 119, in batch_producer
    images, labels, gt_boxes = process_samples(samples)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 95, in process_samples
    image, label, gt = run_transforms(s)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 83, in run_transforms
    args = t(*args)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 159, in __call__
    return self.transforms[pick](data, label, gt)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 148, in __call__
    args = t(*args)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 136, in __call__
    return self.transform(data, label, gt)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 215, in __call__
    data = cv2.cvtColor(data, cv2.COLOR_BGR2HSV)
cv2.error: /tmp/build/80754af9/opencv_1525313247723/work/modules/imgproc/src/color.cpp:11115: error: (-215) (scn == 3 || scn == 4) && (depth == 0 || depth == 5) in function cvtColor

Traceback (most recent call last):
  File "/home/hientt/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/hientt/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 119, in batch_producer
    images, labels, gt_boxes = process_samples(samples)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 95, in process_samples
    image, label, gt = run_transforms(s)
  File "/home/hientt/ssd-tensorflow/training_data.py", line 83, in run_transforms
    args = t(*args)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 159, in __call__
    return self.transforms[pick](data, label, gt)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 148, in __call__
    args = t(*args)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 136, in __call__
    return self.transform(data, label, gt)
  File "/home/hientt/ssd-tensorflow/transforms.py", line 183, in __call__
    data = data.astype(np.float32)
**AttributeError: 'NoneType' object has no attribute 'astype'**
"
Can anyone help me solve this !
Thanks,

**Comment by ljanyst** [comment]
Looks like you don't have the dataset.
