### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by burak3000** [ljanyst/ssd-tensorflow#4]
Thanks for your work. I have to train ssdvgg for custom dataset. I have 5 classes(person, chair, desk, computer and door). I will increase the classes but for now thats all. How can I train on custom dataset? I have Images and Annotations. When I run process_dataset it outputs training-data.pkl, trainval-samples.pkl and valid-samples.pkl. But when I run train.py, after it downloads pretrained model it prints parameters and I am getting following error:

[i] Project name:          test
[i] Data directory:        pascal-voc
[i] VGG directory:         vgg_graph
[i] # epochs:              200
[i] Batch size:            8
[i] Tensorboard directory: tb
[i] Checkpoint interval:   5
[i] Learning rate:         0.0001
[i] Learning rate decay:   0.97
[i] Optimizer  epsilon:    0.1
[i] Weight decay:          0.0005
[i] Continue:              False
[i] Number of workers:     8
Backend TkAgg is interactive backend. Turning interactive mode on.
[i] Creating directory test...
[i] Starting at epoch:     1
[i] Configuring the training data...
[i] # training samples:    6825
[i] # validation samples:  175
[i] # classes:             5
[i] Image size:            Size(w=300, h=300)
2018-01-15 23:04:31.870082: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
[i] Creating the model...
[i] Training...
[i] Epoch  1/200:   0%|          | 0/854 [00:00<?, ?batches/s]Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.3\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.3\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Burak/Desktop/ssd-tensorflow-master/train.py", line 327, in <module>
    sys.exit(main())
  File "C:/Users/Burak/Desktop/ssd-tensorflow-master/train.py", line 241, in main
    desc=description, unit='batches'):
  File "C:\Users\Burak\AppData\Local\Programs\Python\Python35\lib\site-packages\tqdm\_tqdm.py", line 949, in __iter__
    for obj in iterable:
  File "C:/Users/Burak/Desktop/ssd-tensorflow-master\training_data.py", line 166, in gen_batch
    w.start()
  File "C:\Users\Burak\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Burak\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Burak\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\Burak\AppData\Local\Programs\Python\Python35\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Burak\AppData\Local\Programs\Python\Python35\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'TrainingData.__batch_generator.<locals>.batch_producer'

Process finished with exit code 1

**Comment by ljanyst** [comment]
It is likely due to the fact that these generators use multiprocessing and a queue based on POSIX shared memory to speed things up. I think this stuff only works on Linux and Mac and doesn't on Windows. You may try to run the training without parallelism, but it will likely be pretty slow. Pass the `--num-workers 0` parameter to `train.py`. https://github.com/ljanyst/ssd-tensorflow/blob/master/train.py#L76

**Comment by burak3000** [comment]
thanks it started now. I have another question about your code because I didnt get the point. In source_pascal.py there are label and rgb2bgr tuples. What value should I choose for rgb2bgr? Is there any way to findout? Thanks for your answer and time!

**Comment by ljanyst** [comment]
This is just used for drawing boxes on annotated images. Just pick up whatever colors you like.
