### ISSUE TITLE
Issues while using pdb

### ISSUE THREAD

**Issue by apargaon** [ljanyst/ssd-tensorflow#9]
I am having trouble while introducing a breakpoint using:
"import pdb;pdb.set_trace()"
I wanted to know this code is not expected to run with breakpoints? Is there some other library which I need to use to run the code with breakpoints.

Below is the error I am getting:
_______________________________________________________________
-> for s in samples:
(Pdb) 
Process Process-1:
Traceback (most recent call last):
  File "/home/apargaon/anaconda2/envs/test/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/apargaon/anaconda2/envs/test/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/apargaon/ssd/ssd-tensorflow/training_data.py", line 118, in batch_producer
    images, labels, gt_boxes = process_samples(samples)
  File "/home/apargaon/ssd/ssd-tensorflow/training_data.py", line 96, in process_samples
    for s in samples:
  File "/home/apargaon/ssd/ssd-tensorflow/training_data.py", line 96, in process_samples
    for s in samples:
  File "/home/apargaon/anaconda2/envs/test/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/apargaon/anaconda2/envs/test/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
> /home/apargaon/ssd/ssd-tensorflow/training_data.py(96)process_samples()
-> for s in samples:
(Pdb) 
Process Process-2:
Traceback (most recent call last):
  File "/home/apargaon/anaconda2/envs/test/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/apargaon/anaconda2/envs/test/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/apargaon/ssd/ssd-tensorflow/training_data.py", line 118, in batch_producer
    images, labels, gt_boxes = process_samples(samples)
  File "/home/apargaon/ssd/ssd-tensorflow/training_data.py", line 96, in process_samples
    for s in samples:
  File "/home/apargaon/ssd/ssd-tensorflow/training_data.py", line 96, in process_samples
    for s in samples:
  File "/home/apargaon/anaconda2/envs/test/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/apargaon/anaconda2/envs/test/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
> /home/apargaon/ssd/ssd-tensorflow/training_data.py(96)process_samples()
-> for s in samples:
(Pdb) 
Process Process-3:
Traceback (most recent call last):
  File "/home/apargaon/anaconda2/envs/test/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/apargaon/anaconda2/envs/test/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/apargaon/ssd/ssd-tensorflow/training_data.py", line 118, in batch_producer
    images, labels, gt_boxes = process_samples(samples)
  File "/home/apargaon/ssd/ssd-tensorflow/training_data.py", line 96, in process_samples
    for s in samples:
  File "/home/apargaon/ssd/ssd-tensorflow/training_data.py", line 96, in process_samples
    for s in samples:
  File "/home/apargaon/anaconda2/envs/test/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/apargaon/anaconda2/envs/test/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
> /home/apargaon/ssd/ssd-tensorflow/training_data.py(96)process_samples()
-> for s in samples:
(Pdb) 
Process Process-4:
Traceback (most recent call last):
  File "/home/apargaon/anaconda2/envs/test/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/apargaon/anaconda2/envs/test/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/apargaon/ssd/ssd-tensorflow/training_data.py", line 118, in batch_producer
    images, labels, gt_boxes = process_samples(samples)
  File "/home/apargaon/ssd/ssd-tensorflow/training_data.py", line 96, in process_samples
    for s in samples:
  File "/home/apargaon/ssd/ssd-tensorflow/training_data.py", line 96, in process_samples
    for s in samples:
  File "/home/apargaon/anaconda2/envs/test/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/apargaon/anaconda2/envs/test/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

**Comment by ljanyst** [comment]
The support for parallelism in Python is really poor. Try disabling parallel image processing by passing `--num-workers 0` to `train.py`.
